version: '3'
services:
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "15672:15672"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:15672"]
            interval: 30s
            timeout: 10s
            retries: 5
    generate_report:
        build: ./mock-services
        command: ./wait-for-it.sh rabbitmq:5672 -- python generate_report.py
        depends_on:
            - rabbitmq
        environment:
            - AMQP_URI=amqp://guest:guest@rabbitmq
    process_order:
        build: ./mock-services
        command: ./wait-for-it.sh rabbitmq:5672 -- python process_order.py
        depends_on:
            - rabbitmq
        environment:
            - AMQP_URI=amqp://guest:guest@rabbitmq
    inquboui:
        build: ./inqubo-ui
        depends_on:
            - rabbitmq
        environment:
            - AMQP_URI=amqp://guest:guest@rabbitmq
        ports:
            - "3000:3000"
